### PR TITLE
Test most props to avoid unneeded updates.

### PR DESCRIPTION
**Pull request by JasonLG1979**

### CODE REVIEW

**Comment by badcel** [comment]
Are you doing this for compability with some players or just "in case of"? As per definition of the "PropertiesChanged" signal,  everything in there reflects a changed property. If a property stays the same it is simply not included in the signal.

From my point of view this code is a misleading for other developers. If somone takes a look into this app to get information on how to send property change signals from their player it could be assumed that it is in general no problem to send unchanged data in the properties changed signal.

See: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-properties

**Comment by JasonLG1979** [comment]
I did it because people are generally horrible at implementing the mpris spec. 99% of the players out there are broken in at least one way. So basically just in case.

**Comment by JasonLG1979** [comment]
I just wanted to make sure a misbehaving app that sends multiple redundant prop changes doesn't cause needless updates. Many, many Mpris implementations I've looked at do not test their self before sending prop changes as they should.

**Comment by badcel** [comment]
When I started programming for linux I had to discover that very often there is no good documentation. The only reliable source are the applications itself.

To avoid missleading information I would suggst to add some source code comment, which states that this is for applications which are not implemented properly.

**Comment by JasonLG1979** [comment]
I can do that.

**Comment by JasonLG1979** [comment]
If it's alright I'm also going to throw in there that beyond initialization, clients should not have to call back into the interface to get properties like in:

https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/player.js#L439-L513

That whole mess of a function should not be necessary. Players should emit prop changes and signals properly. The extension works correctly even if I comment out all calls to this._refreshProperties with Pithos because we do things right.

**Comment by badcel** [comment]
@JasonLG1979 I'm just a contributor like you. The decision to remove some code is done by eonpatapon. In your specific example I can not give any statement, because I would need to take a deeper look, but I'm lacking the time. But probably @eonpatapon  knows why this code is needed or not.

**Comment by eonpatapon** [comment]
I think that I wansn't listening changes for theses properties and instead checking the value manually (don't ask me why :)). Since then the code has been added in the PropertiesChanged callback but the refreshProperties method wasn't removed.

Back in the days I was doing a lot of workarounds to handle misbehaving players but I'm not sure it's the case here. I'm quite in favor of removing this code (less code is always better), test it with the main players, and see if some people scream :)

Btw, thanks for your work here. It's been a while that I quit using gnome-shell so it was getting hard to maintain this extension.

**Comment by JasonLG1979** [comment]
> Back in the days I was doing a lot of workarounds to handle misbehaving players but I'm not sure it's the case here. I'm quite in favor of removing this code (less code is always better), test it with the main players, and see if some people scream :)

I fear that if it was removed you'd be flooded with bug reports about the extension being broken. Mpris with it's ambiguous docs is somewhat of a black art. Many, many players' implementations are copy pasta(pun intended). The devs do the bare minimum so that it functions but do not truly understand how it should (ideally) work. Hence the need to manually check props and guard against unneeded updates. 

I've been trying to clean that function up by trying to do various things like iterating over an array of props instead of having so much duplicate code and what not but my js fu is still week,lol!!!

>Btw, thanks for your work here. It's been a while that I quit using gnome-shell so it was getting hard to maintain this extension.

No problem just glad to help. I enjoy messing with stuff like this and I must admit my motivations are a bit selfish. I'm a GNOME Shell user and and as you know also a Pithos contributor. I want a top notch experience,lol!!!

**Pull request merged**
