### PR TITLE
Add support for Nuvola Player's MPRIS rating API

### PR DESCRIPTION
**Pull request by fenryxo**
The Nuvola Player's MPRIS interface provides following non-standard
vendor-prefixed rating API:

  * the Player.NuvolaCanRate Boolean property, which is true when rating
    is possible
  * the Player.NuvolaSetRating(Double rating) method to set rating with
    the double value having the same meaning as xesam:userRating in
    Metadata property.

Upstream Issue: tiliado/nuvolaplayer#204

### CODE REVIEW

**Comment by eonpatapon** [comment]
Please don't overload the standard MPRIS player DBUS interface with custom methods.

You should only have to modify the TrackRating class. Like Rhythmbox3 create a DBUs proxy to check your property (NuvolaCanRate) and call NuvolaSetRating(Double rating).

**Comment by fenryxo** [comment]
> You should only have to modify the TrackRating class. Like Rhythmbox3 create a DBUs proxy to check your property (NuvolaCanRate) and call NuvolaSetRating(Double rating).

Done. Thanks for your advice.

**Comment by eonpatapon** [comment]
Can you merge the commits ?

Thanks

**Comment by fenryxo** [comment]
> Can you merge the commits ?

Done :-)

**Comment by fenryxo** [comment]
Hello @eonpatapon. Is there anything I can do to get this feature merged? Thanks.

**Comment by eonpatapon** [comment]
Sorry I forgot about it.

**Pull request merged**
