### PR TITLE
Add Nuvola to known bugs

### PR DESCRIPTION
**Pull request by Frozenfire92**
I have yet to file a bug on nuvola's repo

### CODE REVIEW

**Comment by JasonLG1979** [comment]
@Frozenfire92 is this still a bug with nuvola?

**Comment by Frozenfire92** [comment]
Hi @JasonLG1979 Sorry for the massive delay! It doesn't appear to still be broken

**Comment by JasonLG1979** [comment]
No big deal. I wouldn't call 3 days a massive delay. Thanks for the follow up.

**Comment by Frozenfire92** [comment]
I meant from initial PR submission, but all good :)

**Comment by JasonLG1979** [comment]
Even then a few months isn't that bad since you were given no review or follow up. Feel free to put in more PR's. I will try to help the rest of the team be more responsive in the future.

**Pull request closed without merging**
