### PR TITLE
Many UI changes and improvements.

### PR DESCRIPTION
**Pull request by JasonLG1979**
As dicussed in https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/298

Ratings in particular could use testing. I moved ratings out to it's own widget. Just need to make sure that I didn't break anything.

### CODE REVIEW

**Comment by eonpatapon** [comment]
Tested it quickly. It's looking quite nice.

1. When the player is started (status is stopped) I still can see the ratings widget.

2. I find the double icon (music + status) in the top bar a bit too large.

**Comment by JasonLG1979** [comment]
> When the player is started (status is stopped) I still can see the ratings widget.

No problem, I can fix that.

> I find the double icon (music + status) in the top bar a bit too large

Do you mean the cover/generic audio icon + status in the panel?

How about this for size? The question is bottom of vertically centered? I prefer centered.
screenshot from 2016-12-12 16-19-49
screenshot from 2016-12-12 16-20-10

**Comment by JasonLG1979** [comment]
I think I fixed the ratings showing and hiding I also noticed I forgot about hiding and showing the secondary info I fixed that too I think.

**Comment by JasonLG1979** [comment]
rolled in a fix for https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/258

Users can now set the position of the extension in the system menu.

screenshot from 2016-12-13 00-33-44

**Comment by eonpatapon** [comment]
capture du 2016-12-13 08-47-36

capture du 2016-12-13 08-53-15

Vertically center is fine. It's like the keyboard indicator or the calendar.

Still the gap beetween the music icon and the status icon is too big I think.

**Comment by JasonLG1979** [comment]
OK I can fix that pretty easily.

**Comment by JasonLG1979** [comment]
Better?

**Comment by JasonLG1979** [comment]
Amended to add the ability to hide the stock Mpris applet in GNOME shell versions 3.20 and higher.
Mentioned in https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/301

**Comment by eonpatapon** [comment]
@JasonLG1979 is this PR ready, or you want to change some stuff ?

**Comment by JasonLG1979** [comment]
I'm planing on changing a few small things but right now I'm in the middle of some stuff in Pithos. I'll have it done by the end of the weekend.

**Comment by eonpatapon** [comment]
Ok, no worries, take your time :-)

**Comment by JasonLG1979** [comment]
@badcel I added a PLAYER_THAT_CANT_STOP list so it doesn't hide the stop button permanently for all apps. Could you check this out?

**Comment by JasonLG1979** [comment]
I think I'm done with this if someone would like to test it out?

**Comment by JasonLG1979** [comment]
Ok well I'm going to merge this if anyone notices anything I'll fix it or you can revert it.

**Pull request merged**
