### PR TITLE
Added support for the MPRIS TrackList interface

### PR DESCRIPTION
**Pull request by JasonLG1979**
And a bunch of other good stuff:
1. Asynchronous cover art handling with error checking.

2. Fixed the ratings box.

3. Fixed UI issues.

4. Main player menus behave more like a normal menu item.

5. Use the players symbolic icon in the menu if available. Use the active players symbolic icon in the panel if available.

6. The Indicator Appearance setting change is now instantaneous.

7. The run default setting now instantaneously shows or hides the indicator button in the panel(it only hides it if there isn't an active player) and the indicator button no longer takes up space in the panel if run default is not enabled.

8. The panel button only takes up as much space as absolutely necessary when shown. i.e. no extra space because of the hidden player status icon or text.

### CODE REVIEW

**Comment by JasonLG1979** [comment]
Basically zero of the dozens of players that I have tested support the tracklist interface currently except GNOME Music which crashes on the GoTo method with an internal error. Not my code's fault. The TrackId passes a check to see if it's a known/valid trackId then the player promptly dies a horrible flaming death when it tries to go to the track... I have Blacklisted GNOME Music on the Tracklist interface.

I do however have a branch that will soon (hopefully) be merged into Pithos when i'm done with it with Tracklist support and it functions very well.

screenshot from 2017-02-20 00-49-07

**Comment by JasonLG1979** [comment]
Confirmed in d-feet that the GNOME Music's implementation is borked. If you read the tracks prop in d-feet then use one of the TrackId's in the GoTo method(again still in d-feet) it crashes GNOME Music. I'll file a bug report, incidentally they also for some reason use "/org/mpris/MediaPlayer2/TrackList/" as a prefix for their TrackId's when the spec clearly states not to do that unless you're referring to "NoTrack" i.e. "/org/mpris/MediaPlayer2/TrackList/NoTrack" They should be using something like "/org/gnome/Music/ TrackList/" I'll file a bug report for that too... Hell it's written in Python, I may as well fix it for them...

**Comment by JasonLG1979** [comment]
Reported:
https://bugzilla.gnome.org/show_bug.cgi?id=779052
https://bugzilla.gnome.org/show_bug.cgi?id=779054

**Comment by JasonLG1979** [comment]
Amended to just blacklist GNOME Music for the GoTo method. Users will be able to view the tracklist but won't be able to change tracks in the tracklist menu with GNOME Music.

**Comment by eonpatapon** [comment]
I think that Clementine is supposed to support this interface, did you try ?

I will review this patch this week end, thanks

**Comment by JasonLG1979** [comment]
I'm still trying to shake the bugs out of it. I plan on tweeking on it this weekend. I'm trying to follow spec best I can but it may be a case where they aren't?

**Comment by JasonLG1979** [comment]
A quick question. How do you log stuff? Like for debugging while I'm testing stuff out. I know it will log errors automatically. But how do you log arbitrarily things?

**Comment by eonpatapon** [comment]
You can use global.log() I think. It ends up in my journalctl --user

**Comment by JasonLG1979** [comment]
> I think that Clementine is supposed to support this interface, did you try ?

Another case of claiming to support the interface but taking a crap internally when you actually try to use it...
I get:
```23:03:24.727 WARN  unknown QMetaProperty::read: Unable to handle unregistered datatype 'TrackIds' for property 'mpris::Mpris2::Tracks'```

When I try to get the TrackIds by reading the Tracks Prop...


I Know nothing of C++, but it looks like maybe they forgot to delare the data type?
https://github.com/clementine-player/Clementine/blob/e5ab3e786f9adde12cec3cc90cfe8c1cc6b06320/src/core/mpris2.h#L35-L37

**Comment by JasonLG1979** [comment]
Making great headway upstream with GNOME Music. The fatal crash bug should be fixed by 3.24.

**Comment by JasonLG1979** [comment]
I think I've handled all the errors I can, the best I can. This is set to go AFAIK.

**Comment by JasonLG1979** [comment]
@eonpatapon I also just threw in asynchronous cover art handling with error checking. I definitely makes the UI smoother especially for remote cover images (Spotify) Blocking I/O is basically the devil and no error checking is the devil's brother Steve... This takes care of both of them.

```js
let setCoverIconAsync = function(icon, coverUrl, fallback_icon_name) {
  let file = Gio.File.new_for_uri(coverUrl);
  file.load_contents_async(null, function(source, result) {
    try {
      let bytes = source.load_contents_finish(result)[1];
      icon.gicon = Gio.BytesIcon.new(bytes);
    }
    catch(err) {
      icon.icon_name = fallback_icon_name;
    }
  });
};
```

**Comment by JasonLG1979** [comment]
Amended to add a user setting to show song ratings in the tracklist.
screenshot from 2017-02-26 17-35-46
screenshot from 2017-02-26 17-35-20

**Comment by JasonLG1979** [comment]
Someone better review this before it's able to check your email and login to Facebook,lol!!!

**Comment by JasonLG1979** [comment]
Amended to fix the ratings box. Since it was changed to be a separate widget  we can keep hold onto refs to the nuvola and rhythmbox proxies, instead of recreating them over and over again.

**Comment by JasonLG1979** [comment]
Amended to fix UI issues. Specifically only reserve space for a scrollbar when needed in the playlist and tracklist and never reserve space for scrollbar in the players. Before it was hit and miss if GNOME shell would get it right.

**Comment by JasonLG1979** [comment]
Amended to make the main players menus behave more like a normal menu item. i.e. when you open another menu item in the system it closes a player menu if it's open. I monkey patched menu.emit in the ListSubMenu subclass to capture the 'open-state-changed' signal to prevent the tracklist and playlists menus from closing the player. So now the tracklist and playlists menu will only close each other and are only closed by each other. The effect is that say the playlists menu is open and you click on the networks menu in the system menu. The player will close like a normal menu item. If you click back on the player it will opened and the tracklist will still be open. When the system menu is initially opened the active player if any will be opened(since closing the system menu closes all it's containing menus). whatever playlists or tracklist menus that were open will still be open. Basically the parent menu can control the player menus but only we can control the playlists and tracklist submenus.

**Comment by JasonLG1979** [comment]
And I also moved parseMetadata to lib since it's used by both the main player menu and the tracklist items now.

**Comment by JasonLG1979** [comment]
Amended to use the player's symbolic icon in the menu if available otherwise fallback to the generic audio icon. Also use the active player's symbolic icon in the panel if available otherwise fallback to the generic icon. If the user has the current cover set as the panel icon the priority is current cover, player's symbolic icon and finally generic icon.

workspace 1_003

**Comment by JasonLG1979** [comment]
@eonpatapon I'm trying to figure out how to programmatically scroll so that the current playlist and track are snapped into view on changes. Any ideas? I really can't find an easy way to do it.

**Comment by JasonLG1979** [comment]
Amended to make changing the Indicator Appearance setting change instantaneous instead of not taking effect until the next song.

**Comment by JasonLG1979** [comment]
Amended to fix the indicator button taking up space even though there's nothing in it when the run default setting is set to false. And the run default setting now instantaneously shows or hides the indicator button.

**Comment by eonpatapon** [comment]
Don't know how to programmatically scroll...

**Comment by JasonLG1979** [comment]
> Don't know how to programmatically scroll...

Don't think you can. From what I understand you'd need to send a Clutter.Event and you can't generate them in Gjs.

**Comment by JasonLG1979** [comment]
After tweaking the hell out of the UI bits to make them behave, I'm not very impressed with it's implementation of Clutter/St widgets. Very limiting.

**Pull request merged**
