### PR TITLE
Dynamic aggregate menu icon

### PR DESCRIPTION
**Pull request by badcel**
Add a dynamic aggregate menu icon.

Tested with VLC and webmusic. Should be tested by more people to avoid breaking s.th..

### CODE REVIEW

**Comment by eonpatapon** [comment]
Thanks for your work.

Although the idea is good to have a dynamic icon I'm not fan of the widget. The problem is that you have to make the icons smaller to keep the alignment with the other icons but it looks bad in my opinion.

I made a test to replace the generic music icon with just playback icons (play/pause/stop) and I think it works better (it's in the dynamic-icon branch). Let me know what you think.

Thanks

**Comment by badcel** [comment]
From my point of view an important bit of information is lost. Now the icon only shows the status but not the functionality of the menu itself.

I agree that a smaller icon looks out of style.

I took a look into the high contrast theme. There they created several icons to display the status (e.g. for disabled network, bluetooth, weather, touchpad, etc). Perhaps a possibility would be to remove one half of the icon and add the status information instead:

test

**Comment by eonpatapon** [comment]
An icon like this could be nice indeed

**Comment by badcel** [comment]
I did some small tests but the design of the note's top is looking out of place for me. If the rectangle on the top is ommited it's lacking something. What do you think?

**Comment by JasonLG1979** [comment]
@badcel and/or @eonpatapon is this still relevant?

**Comment by badcel** [comment]
I think it is not relevant.

**Comment by JasonLG1979** [comment]
Right on. I or you can close it than?

**Comment by badcel** [comment]
Not relevant, making the menu dynamic should be handled individually and not in the same way like the tray icon.

**Pull request closed without merging**
